#' Extracts the data expression matrix from object
#'
#' This function extracts the data expression matrix from object as a
#' non-sparse matrix
#'
#' @param scObj A Seurat object, SingleCellExperiment object, or expression matrix
#'
#' @return An expression matrix
#'
#' @export
#'
expMat <- function(scObj)
  UseMethod(generic='expMat', object=scObj)

#' Output CSOA scores
#'
#' This function returns the output generated by CSOA
#'
#' @inheritParams generateOverlaps
#' @param ... Arguments passed to other methods
#'
#' @return A CSOA score assigned for each cell
#'
#' @export
#'
storeScore <- function(scObj, ...)
  UseMethod(generic='storeScore', object=scObj)

