#' @importFrom stats quantile
#'
NULL


#' Generates cell quantiles of gene expression for input genes
#'
#' This function takes a Seurat object or expression matrix of matrix class,
#' a list of genes and a number of quantiles. For each gene, the cells
#' where the gene has a non-zero expression are arranged into quantiles based on
#' the expression of the gene.
#'
#' @inheritParams expMat
#' @param genes Vector of genes. Must include at least two genes
#' @param nQuantiles A positive integer
#'
#' @return A named list of length equal to the length of the genes array.
#' Each of its elements is a list comprising nQuantiles character arrays.
#'
#' @export
#'
fullQuantileSets <- function(scObj, genes, nQuantiles=10){
  if (!min(is(genes)[1:2] == c('character', 'vector')) | length(genes) < 2)
    stop('genes must be a character vector of length >= 2')
  if (!isPosInt(nQuantiles))
    stop('nQuantiles must be a positive integer')
  expression <- expMat(scObj)
  message('Computing quantiles...')
  expList <- lapply(genes, function(x){
    geneExp <- expression[x, ]
    geneExp <- geneExp[geneExp > 0]
    quantiles <- splitQuantile(geneExp, nQuantiles)
    return(lapply(1:nQuantiles, function(y) return(names(geneExp[which(quantiles == y)]))))
  })
  names(expList) <- genes
  return(expList)
}

#' Selects the cells within the top quantile of gene expression
#'
#' This function takes a list generated using fullQuantileSets, consisting of
#' lists of cell names and named using gene names, and retains the top-quantile
#' cells from each list.
#'
#' @param quantileCellSets A list of lists of character arrays generated by
#' fullQuantileSets
#'
#' @return A named list of character arrays storing the cells from the
#' top expression quantile for each gene in the names of the list.
#'
#' @export
#'
topQuantileSets <- function(quantileCellSets){
  nQuantiles <- length(quantileCellSets[[1]])
  topQuantiles <- lapply(quantileCellSets, function(x) return(x[[nQuantiles]]))
  return(topQuantiles)
}
